### ISSUE TITLE
Umlaute in Oberfläche

### ISSUE THREAD

**Issue by 0815Lagerregal** [H2CK/hm_caldav#1]
Hi, 
nur ne Kleinigkeit: Umlaute werden in der (Konfigurations)Oberfläche nicht korrekt angezeigt

Beispiel:
CalDav Integration fï¿½r HomeMatic - hm_caldav

**Comment by H2CK** [comment]
Sollte mit der nächsten Version gefixed sein.

**Comment by H2CK** [comment]
Fixed with version 0.6.
