### ISSUE TITLE
Feature Request: Variable ob morgen der Event true/false ist

### ISSUE THREAD

**Issue by 0815Lagerregal** [H2CK/hm_caldav#2]
Aktuell klappt alles gut und ich kann sehen, ob mein Event jetzt gerade stattfindet.
Im Hinblick auf Planung wäre es allerdings gut zu wissen, ob der Event MORGEN geplant ist.
(So könnte man am Abend vorher die Mülltonne rausbringen und sich daran erinnern lassen)

Eine neue Variable mit Variable-tomorrow oder so etwas wäre gut.

**Comment by 0815Lagerregal** [comment]
P.S.: Echt ein schönes Tool!! So kann ich endlich problemlos und simple einen ICS Kalender einbinden!!

**Comment by H2CK** [comment]
Eine mögliche Umsetzung werde ich in den nächsten Tagen analysieren.

**Comment by H2CK** [comment]
Please test version 0.6. The functionality should be provided in this version.

**Comment by 0815Lagerregal** [comment]
Hi,

super genial, die neuen Variablen werden kreiert:
Requesting caldav data from server ...
  Creating CCU variable 'Test.Belegt' (bool)... ok.
  Creating CCU variable 'Test.Belegt-TODAY' (bool)... ok.
  Creating CCU variable 'Test.Belegt-TOMORROW' (bool)... ok.
Finished processing.

Die Abfrage aktualisiert allerdings nur eine (die bisherige) Variable:
Requesting caldav data from server ...
Ongoning event: Belegt
 from: 20210117 T: 000000 until: 20210122 T: 000000
  Setting CCU variable 'Test.Belegt': 'true'... ok.
Finished processing.

Wenn das noch klappt wäre ich extrem glücklich!! :-)

**Comment by H2CK** [comment]
Bitte teste mal die Version 0.7. Ich habe noch einige Probleme gefunden.

**Comment by 0815Lagerregal** [comment]
Hi,

Die Variablen TODAY und TOMORROW werden nicht immer aktualisiert. Leider habe ich hier auch kein Muster herausgefunden.
Zuerst dachte ich fehlt nur tomorrow (siehe log), danach wurde aber nur noch die default Variable aktualisiert und today und tomorrow nicht.


  == Thu Jan 21 13:11:46 CET 2021 ===================================
Processing CalDav: xxx
Requesting caldav data from server ...
  Creating CCU variable 'Test.Belegt' (bool)... ok.
  Creating CCU variable 'Test.Belegt-TODAY' (bool)... ok.
  Creating CCU variable 'Test.Belegt-TOMORROW' (bool)... ok.
Ongoning event: Belegt
 from: 20210121 T: 000000 until: 20210122 T: 000000
Today event: Belegt
 from: 20210121 T: 000000 until: 20210122 T: 000000
  Setting CCU variable 'Test.Belegt': 'true'... ok.
  Setting CCU variable 'Test.Belegt-TODAY': 'true'... ok.
Finished processing.

**Comment by H2CK** [comment]
Das Datum von morgen (TOMORROW) sollte jetzt (mit der Version 0.8) auch sicher mit dem date Kommando der Busybox der CCU generiert werden können. Da die date Funktion unter der CCU mit Busybox sehr eingeschränkt ist, war das nicht immer sicher möglich. 
Weiterhin habe ich das Logging erweitert. So lange sich keine Änderung am Status der Variablen ergibt, wird diese in der CCU auch nicht aktualisiert. Erst wenn sich der Wert der Variablen verändert, wird diese Änderung auch in die CCU Variable geschrieben. Dies sollte jetzt auch im Logging klar dargestellt werden.

**Comment by 0815Lagerregal** [comment]
Hi,
Variablen wurden angelegt, allerdings können diese nun nicht gelesen werden.

Processing CalDav: xxx.ics
  No update of CCU variable 'Test.Belegt' necessary, since state is already in target state 'false'.
ERROR: Variable 'Test.-TODAY' can not be read from CCU.
ERROR: Variable 'Test.-TOMORROW' can not be read from CCU.
Finished processing.
== Sat Jan 23 13:17:24 CET 2021 ===================================
== Sat Jan 23 13:17:18 CET 2021 ===================================
Processing CalDav: xxx.ics
Requesting caldav data from server ...
  Creating CCU variable 'Test.Belegt' (bool)... ok.
  Creating CCU variable 'Test.Belegt-TODAY' (bool)... ok.
  Creating CCU variable 'Test.Belegt-TOMORROW' (bool)... ok.
  No update of CCU variable 'Test.Belegt' necessary, since state is already in target state 'false'.
ERROR: Variable 'Test.-TODAY' can not be read from CCU.
ERROR: Variable 'Test.-TOMORROW' can not be read from CCU.
Finished processing.

**Comment by H2CK** [comment]
Leider wurden die Variablen im Script nicht sauber initialisiert. Mit der Version 0.9 sollte das behoben sein und hoffentlich die Funktion bereitstehen.

**Comment by 0815Lagerregal** [comment]
Hi, habe jetzt einige Test mit wechselnden ics-Dateien gemacht.
Nach dem Wechsel der CalDav Url werden die Variablen richtig gesetzt, bei Bedarf so gelassen oder verändert.
  Requesting caldav data from server ...
Ongoning event: Belegt
 from: 20210123 T: 000000 until: 20210125 T: 000000
Today event: Belegt
 from: 20210123 T: 000000 until: 20210125 T: 000000
Tomorrow event: Belegt
 from: 20210123 T: 000000 until: 20210125 T: 000000
  Setting CCU variable 'Test.Belegt': 'true'... ok.
  Setting CCU variable 'Test.Belegt-TOMORROW': 'true'... ok.
  Setting CCU variable 'Test.Belegt-TODAY': 'true'... ok.

Ein komisches Verhalten hatte ich bei diesem Testcase (ohne und TODAY sind unterschiedlich):
Requesting caldav data from server ...
Today event: Belegt
 from: 20210123 T: 000000 until: 20210123 T: 000000
  No update of CCU variable 'Test.Belegt' necessary, since state is already in target state 'false'.
  No update of CCU variable 'Test.Belegt-TOMORROW' necessary, since state is already in target state 'false'.
  Setting CCU variable 'Test.Belegt-TODAY': 'true'... ok.
...Die erste Variable wäre aber für mich auch nicht relevant, da TOMORROW und TODAY gut funktionieren und die für mich überflüssig ist.

Egal, für mich ist das jetzt so benutzbar! Vielen vielen Dank!!
