### ISSUE TITLE
Feature Request: Erhöhung des Intervalls der automatischen Ausführung

### ISSUE THREAD

**Issue by 0815Lagerregal** [H2CK/hm_caldav#3]
Eine Erhöhung des Intervalls von aktuell 30 Minuten wäre sinnvoll.
Idee ist, dass bei Ganztagesterminen auch eine tägliche Aktualisierung ausreicht und Ressourcen schont.
Ähnliche Werte wie bei ICS Aktualisierung wären gut.
(by the way: der Schieberegler der ICS Aktualisierung gibt die unterschiedlichsten Werte beim Schieben)

**Comment by H2CK** [comment]
Dieses Intervall legt fest wann geprüft wird, ob ein Termin gerade läuft. Je höher der Wert, desto ungenauer erfolgt das setzen der Variable, dass ein Termin gerade stattfindet. Beispiel: 
Ein Termin startet um 8:00:00 Uhr.
Liegt das Intervall bei 15 Sekunden, so erfolgt das Setzen der Variable spätestens um 8:00:15 Uhr.
Liegt das Intervall bei 30 Minuten (aktuelles Maximum), so erfolgt das Setzen der Variable, dass der Termin stattfindet, ggf. spätestens erst um 8:30:00 Uhr
Wenn das Intervall jetzt auf "einmal am Tag" gestellt wird, werden Termine kürzer als ein Tag ggf. gar nicht mehr in Variablen signalisiert. Auch ein ganztägiges Event könnte dann ggf. erst in den letzten Minuten des Tages auf aktiv gesetzt werden und erst wieder den nächsten Tag (wenn das Event gar nicht mehr stattfindet) in der Variable gelöscht werden.

Daher ist es aus meiner Sicht nicht sinnvoll dieses Intervall über die 30 Minuten hinaus auszudehnen. Gerade wenn man nur ganztägige Ereignisse mit der Erweiterung nutzen möchte, sollte 30 Minuten eine ausreichende Präzision geben.
Bei der Überwachung von stündlichen Terminen sollte m.E eher eine Präzision von Sekunden bzw. wenigen Minuten gewählt werden.

Alternativ könnte, wenn nur ganztägige Events betrachtet werden, eine Prüfung des Kalender immer um 0:00:01 Uhr erfolgen.
Das müsste aber über einen (cron) Job angestoßen werden. Die Erweiterung kann jedenfalls keine Prüfung zu einer bestimmten Uhrzeit ausführen.

Zu dem anderen Thema: Die Schieberegler schaue ich mir nochmal an.

**Comment by H2CK** [comment]
Wie beschrieben ist eine Umsetzung in der gewünschten Form nicht möglich.
