### ISSUE TITLE
Feature Request: Wiederholungstermine

### ISSUE THREAD

**Issue by berlingser** [H2CK/hm_caldav#4]
Ich bin begeistert von dem AddOn, es läuft gut und stabil. Dafür schonmal Vielen Dank!

Es wäre schön, wenn auch Serientermine funktionieren würden. Zur Zeit muss ich jeden Termin regelmäßig kopieren.

Terminserien scheinen nicht erkannt zu werden. Ist das lösbar?

**Comment by H2CK** [comment]
Eine Erweiterung, damit auch Serientermine genutzt werden können, sollte bestimmt möglich sein. Eine zeitnahe Anpassung des AddOns kann ich aktuell jedoch nicht garantieren.

**Comment by berlingser** [comment]
Danke für die zeitnahe Rückmeldung. Es ist ja ein Wunsch.
Wenn es irgendwann klappt, würde ich mich riesig freuen.

**Comment by H2CK** [comment]
Nach einiger weitergehender Analyse musste ich feststellen, dass die zu implementierende Logik zur Auswertung der RRULE in einem VEVENT an die Grenzen des Moduls der CCU2 stößt. (Das Modul sollte auch weiterhin auf der CCU2 nutzbar bleiben)
Falls hier bereits eine CCU3 genutzt wird, sollte stattdessen besser NodeRED installiert/genutzt werden. Die dort verfügbare Erweiterung [kalendar-events](https://naimo84.github.io/kalender-events/) bietet hier bereits jegliche Funktionalität auch wiederkehrende Termine auswerten zu können und darauf basiert Aktionen in der CCU auszulösen bzw. Variablen zu setzen.
