### ISSUE TITLE
Feature request: Eingeladene Termine triggern eine Aktion

### ISSUE THREAD

**Issue by MPCapricorn** [H2CK/hm_caldav#5]
Hallo! Ich möchte das Addon nutzen, um CCU-Aktionen mittels Terminen im privaten Kalender auszulösen, die allerdings nicht im Kalender selbst erstellt werden, sondern von einer Einladung eines fremden Teilnehmers kommen (Ich pflege alle Termine im Arbeitskalender, den ich aber wegen Security nicht privat einbinden kann - daher will ich Einladungen von dort an den privaten Kalender senden um das gleiche Ziel zu erreichen).
Das schlägt aktuell fehl. Ein eingeladener Termin von extern führt nicht zu einem "today active" in der Raspberrymatic, ein exakt gleichlautender Termin lokal erstellt im selben Kalender hingegen schon. Ich dachte, dass Addon schaut nur auf den String im Titel des Termins.

Gibt es eine Möglichkeit das passend zu erweitern?

**Comment by H2CK** [comment]
Dieses CCU-Addon lädt den CalDAV Kalender als Datei herunter und überprüft dann nur die VEVENT Komponente im CalDAV Kalender (Startzeit, Endzeit und Summary). Für mich ist derzeit nicht klar, wie Einladungen im CalDAV Kalender abgebildet werden.
Nach meinem Verständnis wird eine versendete Einladung erst ein VEVENT, wenn die Einladung angenommen wurde. Zuvor liegt diese als VFREEBUSY Komponente im CalDAV Kalender vor.

Aufgrund der Limitierungen der CCU1/2 ist dieses AddOn im wesentlichen als Shell Skript ausgeführt und Erweiterungen sind hier nur mit einem gewissen Aufwand möglich (Das gilt auch für die VFREEBUSY Komponente). Auch ist auf CCU1/2 keine hohe Sicherheit gegeben, da die SSL Bibliotheken dieser CCU Versionen erheblich veraltet sind und keine Zertifikatsprüfung erfolgt.

Falls hier bereits eine CCU3 genutzt wird, könnte NodeRED via [RedMatic](https://www.homematic-inside.de/software/redmatic) installiert/genutzt werden. Die dort verfügbare Erweiterung [kalendar-events](https://naimo84.github.io/kalender-events/) bietet hier bereits eine umfangreiche Funktionalität, um Kalender auswerten zu können und entsprechende Aktionen anzustoßen.

Ich werde für eine Erweiterung des AddOns leider keine Zeit finden. Falls jemand gerne die Entwicklung dieser Funktionalität übernehmen möchte, ist er hierzu gerne eingeladen (Änderungen können via Pull Request gerne eingebracht werden).

**Comment by MPCapricorn** [comment]
Ok, danke für den Input, verstehe ich. Dann schaue ich mich bei NodeRED um.
